{
 "title": "Aktuell",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Wohnen", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Raphael",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "energyTele",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "OfficeRaphael" }
     ]
    }
   ]
  },
  {
   "title": "Thomas",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "energyTele",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "OfficeThomas" }
     ]
    }
   ]
  },
  {
   "title": "TV Wohnen",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "energyTele",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "TvWohnen" }
     ]
    }
   ]
  },
  {
   "title": "3D Schrank",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "energyTele",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "3DSchrank" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Aktuell",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energyTele",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "OfficeRaphael" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Heute",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energyTele",
     "select": [
      [
       { "params": [ "today" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "OfficeRaphael" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Gestern",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energyTele",
     "select": [
      [
       { "params": [ "yesterday" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "OfficeRaphael" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Aktuell",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energyTele",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "OfficeThomas" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Heute",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energyTele",
     "select": [
      [
       { "params": [ "today" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "OfficeThomas" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Gestern",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energyTele",
     "select": [
      [
       { "params": [ "yesterday" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "OfficeThomas" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Aktuell",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energyTele",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "TvWohnen" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Heute",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energyTele",
     "select": [
      [
       { "params": [ "today" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "TvWohnen" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Gestern",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energyTele",
     "select": [
      [
       { "params": [ "yesterday" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "TvWohnen" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Aktuell",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energyTele",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "3DSchrank" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Heute",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energyTele",
     "select": [
      [
       { "params": [ "today" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "3DSchrank" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Gestern",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energyTele",
     "select": [
      [
       { "params": [ "yesterday" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "3DSchrank" }
     ]
    }
   ]
  },
  { "title": "Keller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Tiefkühlschrank",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "energyTele",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "TiefKuehlKeller" }
     ]
    }
   ]
  },
  {
   "title": "Kühlschrank",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "energyTele",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "KuehlKeller" }
     ]
    }
   ]
  },
  {
   "title": "Heizung",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "energyTele",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "Heizung" }
     ]
    }
   ]
  },
  { "title": "Panels", "type": "dashlist", "gridPos": { "h": 8, "w": 4, "x": 18, "y": 10 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Aktuell",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energyTele",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "TiefKuehlKeller" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Heute",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energyTele",
     "select": [
      [
       { "params": [ "today" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "TiefKuehlKeller" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Gestern",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energyTele",
     "select": [
      [
       { "params": [ "yesterday" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "TiefKuehlKeller" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Aktuell",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energyTele",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "KuehlKeller" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Heute",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energyTele",
     "select": [
      [
       { "params": [ "today" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "KuehlKeller" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Gestern",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energyTele",
     "select": [
      [
       { "params": [ "yesterday" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "KuehlKeller" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Aktuell",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energyTele",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "Heizung" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Heute",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energyTele",
     "select": [
      [
       { "params": [ "today" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "Heizung" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Gestern",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energyTele",
     "select": [
      [
       { "params": [ "yesterday" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "Heizung" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energyTele",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "TvWohnen" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energyTele",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "Heizung" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energyTele",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "TiefKuehlKeller" }
     ]
    }
   ]
  },
  {
   "title": "Waschen",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "energyTele",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "Waschen" }
     ]
    }
   ]
  },
  {
   "title": "Trockner",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "energyTele",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "Trockner" }
     ]
    }
   ]
  },
  {
   "title": "Zähler - Aktuell",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energyPwrGrid",
     "select": [
      [
       { "params": [ "energy" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Zähler - Gestern",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "energyDaily",
     "select": [
      [
       { "params": [ "today" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "time", "operator": ">", "value": "now() - 24h" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Aktuell",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energyTele",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "Waschen" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Heute",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energyTele",
     "select": [
      [
       { "params": [ "today" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "Waschen" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Gestern",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energyTele",
     "select": [
      [
       { "params": [ "yesterday" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "Waschen" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Aktuell",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energyTele",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "Trockner" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Heute",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energyTele",
     "select": [
      [
       { "params": [ "today" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "Trockner" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Gestern",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energyTele",
     "select": [
      [
       { "params": [ "yesterday" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "Trockner" }
     ]
    }
   ]
  }
 ]
}